### ISSUE TITLE
Access Required

### ISSUE THREAD

**Issue by jhemaniplume** [open-afc-project/openafc#101]
Hello,
We are from Plume. We would like to get access to the below github repository. Please let us know how to proceed. 
https://github.com/open-afc-project/openafc
Also could you please share an email id through which further communication can be done.

**Comment by mgelman-rkf** [comment]
@jhemaniplume Hello.  Is there a particular issue you would like to contribute to?  If so, please create that issue and you should be able to create a branch to work it.  Please see https://github.com/open-afc-project/openafc#contributing for our preferred process.

If you just need read access, everyone should be able to clone the repository.  Please follow up here if that is not the case.

We usually try to keep communications here in the repository so all of our administrators from multiple organizations can see what is happening.  Do you have a specific question?  We can try to route it to someone who can help if we know what you are looking for.

**Comment by jhemaniplume** [comment]
Hi,
Thank you for the response. 
I am actually getting stuck at these commands. It is showing some error.
below is the picture of from which step I am getting stuck.
<img width="903" alt="Screenshot 2024-07-05 at 6 00 38 PM" src="https://github.com/open-afc-project/openafc/assets/174602315/1187e09e-397a-48e6-a231-09bb00dc7297">

I am getting the output like this,
if I run the command in the shell it is coming like this.
<img width="903" alt="Screenshot 2024-07-05 at 6 03 56 PM" src="https://github.com/open-afc-project/openafc/assets/174602315/4a1688b9-4687-4b00-8cee-d86486000831">

And after comming out of the command it is coming like this:
[@wcc-afc-01 work/dimar/open-afc] > ls -l build/src/afc-engine/afc-engine
-rwxr-xr-x. 1 dr942120 dr942120 4073528 Mar  8 04:03 build/src/afc-engine/afc-engine
zsh: bad pattern: [@wcc-afc-01

If i go to the next command in the documentation which says running in the worker directory I am getting this ouput;

docker run --rm -it --user `id -u`:`id -g` --group-add `id -G | sed "s/ / --group-add /g"` -v `pwd`:/wd/afc -v /opt/afc/worker:latest sh
Unable to find image 'sh:latest' locally
docker: Error response from daemon: pull access denied for sh, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

What should be the next step. I am getting stuck here

**Comment by mgelman-rkf** [comment]
So there's a couple things I see going on here:

- We have a bug in the documentation - the second line ("-rwxr-xr-x. 1 dr942120 dr942120 [...]") is the expected output from the first.  The close tag from the markdown quote is misplaced.  I'll add that correction to our list.
- Instead of building the engine separately, I would recommend you follow the instructions to get the full system up and running with docker compose, skipping the section "Building OpenAFC engine".  I can see why the order is confusing to an unfamiliar developer; my apologies. Building the engine separately is a digression from just getting the system up and running; it was at that point in the documentation for historical reasons. I will add a correction to our list as well.

I will mention there is also a known issue where the build tags are wrong in the final step of [celery-worker-prereq-containers](https://github.com/open-afc-project/openafc?tab=readme-ov-file#celery-worker-prereq-containers), the PRINST_TAG and BLD_TAG should be "latest" not "local".

Hope this helps

**Comment by jhemaniplume** [comment]
Hi,
Thank you for your quick responses. I am facing another difficulty. As you said, I skipped the "Building OpenAFC engine" and moved to the next steps. Now after creating the .env file, and after running the docker compose command this is the output I am getting. 
[
<img width="903" alt="Screenshot 2024-07-08 at 4 35 42 PM" src="https://github.com/open-afc-project/openafc/assets/174602315/6611ec05-c46d-457b-8aec-dba0fe5884c8">
](url)

If you could help me out where I am getting it wrong or where the error is coming. I am assuming that there is some access that keeps on getting denied.

**Comment by mgelman-rkf** [comment]
How familiar are you with docker and docker compose? 
Did all the local images build correctly? 
als_kafka should have built locally in that step and not require a download.

**Comment by jhemaniplume** [comment]
I see where the problem is. The docker didnt build the local images correctly. Should I delete the Docker and reinstall it. would that help, or should I manually build the local images. Could you help out with the next steps.
Thanking in Advance

**Comment by mgelman-rkf** [comment]
You should build the images manually.  Once the images are built, you should be able to run the docker compose command.

**Comment by jhemaniplume** [comment]
Hi, I have tried to run everything again and checked the docker as well. I am still facing a similar issue. What should be done?

<img width="677" alt="image" src="https://github.com/user-attachments/assets/6f4abbe6-37bf-414f-a2d9-704b9a35d207">

**Comment by mgelman-rkf** [comment]
My apologies for the delayed reply; I was travelling for another project.

I think I see what the issue might be - are you setting PRIV_REPO and PUB_REPO to your repository in the .env file?  I suspect not and so it's reaching out to the repository that we use in regression testing which you would not have access to. You might want to compare with the simpler docker-compose described in the top level README file.

I think we do need to have a  real-time discussion to get you up and running and the problems you're having may be beyond the scope of what I can do here.  My contact is mgelman@rkf-eng.com, please email me; my manager will be back next week and we can discuss with her what level of support we can provide.

**Comment by mgelman-rkf** [comment]
Got the system minimally functional
