### ISSUE TITLE
Open AFC for Testing

### ISSUE THREAD

**Issue by jhemaniplume** [open-afc-project/openafc#127]
I have been able to get the server up and running on my device. Would it be possible to get certificates which I can use on the device to connect to the open AFC server. It is purely for testing purpose only. Or are there any possiblities for me to get a temporary license for the same.

**Comment by mgelman-rkf** [comment]
We don't provide any certificates - you can use self signed certificates or use a CA to generate them.  There are some sample certificate files in the source tree.
