### ISSUE TITLE
Does US.kml file in population database need any post-processing for afc-engine to parse it

### ISSUE THREAD

**Issue by diptivete** [open-afc-project/openafc#185]
Hello,

Is there any post-processing to be done on US.kml (country boundary) file after downloading from here: https://public.opendatasoft.com/explore/dataset/world-administrative-boundaries/export/?flg=en-us for afc-engine module to parse it correctly?

I read this note in database_readme - country.KML: there is some post-processing done that is not documented here as we are moving to using a different processing.

Thanks,
Dipti

**Comment by mmandellrkf** [comment]
Yes, significant processing has been done on the raw data downloaded to create US.kml.  In particular, the shapefile downloaded contains a polygon for the USA with 11092 points.  Such a large number of points is not necessary for the afc-engine, and would impact the performance of the afc-engine.  Issue " Country Boundary Fix #135" is currently being worked on and will add to the git repository the C++ program, and associated documentation, used to process downloaded shapefiles and create the kml file for subsequent use by the afc-engine.

**Comment by diptivete** [comment]
@mmandellrkf Thanks for the clarification. In the meantime, could you please help provide processed US kml file that I can use? 
I'm encountering "ERROR: multiple <Placemark>'s found" error while trying to execute AFC service test (availableSpectrumInquiryInternal message) in ULS downloader post FS database download. 

Thank you for your time & support.

**Comment by farinazedalat** [comment]
Please see attached. I had to zip it to allow attachment. Please unzip first. Note that once the issue #135 is committed, a more precise country boundary will be generated.
[US.zip](https://github.com/user-attachments/files/17285923/US.zip)

**Comment by diptivete** [comment]
Thank you @farinazedalat. Understood, will watch issue #135.
