### ISSUE TITLE
3DEP terrain files resolution anomalies

### ISSUE THREAD

**Issue by mmandellrkf** [open-afc-project/openafc#189]
Some of the WGS84 3DEP terrain files have the following issues:
(1) Grid spacing is not exactly 1 arcsec
(2) Grid is not aligned with origin coordinates at integer multiple of 1 arcsec

The spacings and alignments are very close, but not exact, suggesting this is possibly due to precision/rounding.  Furthermore, in the afc-engine these precision issues result in incorrect terrain height lookups.  These WGS84 files were converted from NAD83 using the script to_wgs84.py.  The original NAD83 files do not have these precision issues.  The script to_wgs84.py uses gdalwarp to perform the conversion to WGS84.  It has been observed that the gdal version as well as specific command line options passed to gdalwarp impact whether or not the conversion result has the above resolution anomalies.

As a specific example, the file USGS_1_n50w120.tif has resolution anomalies that have impacted ISED's AFC certification.

Recommended that:
(1) The script to_wgs84.py modified so resulting WGS84 files do not have these resolution anomalies.
(2) In the afc-engine, the CachedGdal data structure modified to either (a) properly treat raster files with arbitrary alignment/grid spacing OR  (b) detect improper alignment/grid spacing and report error.

**Comment by farinazedalat** [comment]
Hi @FedorSherstyukBroadcom ,
We completed fixing the script to_wgs84.py (item 1 above).
Would you please work on item 2 so we can detect such issues in the future? This doesn't have same urgency as the first item that we completed.
Thank you!

**Comment by mmandellrkf** [comment]
The issue with CachedGdal can be illustrated with the following example.  An RLAN is placed at the coordinates:
```
LON = -119.6109722222222 deg
LAT =   49.0898611111111 deg
```

Converting these values to deg, min, sec gives:
```
LON = -119 deg, 36 min, 39.5 sec
LAT =   49 deg,  5 min, 23.5 sec
```

Note that both the lon and lat coordinates are halfway between integer arcsec values, so the RLAN position is in the center of a 1arcsec x 1 arcsec grid region.

Running afc-engine and looking at exc_thr.csv, it can be seen that:

```
RLAN_TERRAIN_HEIGHT (m) = 859.829284667969 m
```

and this value comes from 3DEP.  More specifically, this value comes from the file: ```USGS_1_n50w120.tif```.

Manually checking the height at these lon/lat coordinates using ```gdallocationinfo``` gives:

```
yarmouth% gdallocationinfo -geoloc USGS_1_n50w120.tif -119.610972222222 49.0898611111111
Report:
  Location: (1406P,3282L)
  Band 1:
    Value: 862.39013671875
```

This value of ```862.39``` is different from the ```859.82``` that is seen in the afc-engine.

Next, qgis is used to further investigate.  Attached is a screenshot of qgis, zoomed in on the region of the RLAN position.  The red dot indicates the RLAN position and it can be seen to, in fact, be in the center of a 1arcsec x 1arcsec region.  The heights for several 1arcsec x 1arcsec regions are indicated in the screenshot.  Note that:
* The height reported by qgis for the 1arcsec x 1arcsec region containing the RLAN is ```862.39014``` which agrees with what was reported by gdallocationinfo for the RLAN position.
* From the RLAN position, moving 2 arcsecs east, and 1 arcsec south the height reported by qgis is ```859.8293``` which is what is seen in the afc-engine.

This discrepancy has not been observed in the past.  Using gdalinfo to further investigate the file ```USGS_1_n50w120.tif``` by running ```gdalinfo USGS_1_n50w120.tif```, gdalinfo reports:

```
Origin = (-120.001667276070947,50.001666666666672)
Pixel Size = (0.000277776426851,-0.000277776426851)
```

Converting these to deg, min, sec gives:

```
Origin Lon = -120 deg, 0 min, 6.0021938 sec
Origin Lat =   50 deg, 0 min 6.000000000019200 sec

Pixel Size Lon =  .999995136663600 sec
Pixel Size Lat = -.999995136663600 sec
```

Here it can be seen that the origin coordinates are close to being integer multiples of 1 arcsec, but not to 64-bit precision, especially the origin longitude with ```0.0021938``` sec deviation from an integer which far exceeds what would be expected for 64-bit precision.  Also, the pixel sizes, which should be 1 arcsec, have 5 nine's of precision.  This deviation far exceeds what would be expected for 64-bit precision.

This has been extensively tested for numerous coordinate positions over several 3DEP tif files, and it has been observed that when both the origin coordinates and pixel sizes are aligned with full 64-bit precision, the afc-engine functions properly in that the height seen in the afc-engine agrees with gdallocationinfo and qgis.  The script ```to_wgs84.py``` has been modified so that the newly generated 3DEP tif files are forced to align origin coordinates and pixel sizes with full 64-bit precision.  I further recommend that the CachedGdal implementation be modified to either:

(a) Properly treat raster files that are not exactly aligned to a 1arcsec grid and return results consistent with gdallocationinfo and qgis.

or

(b) Detect a raster file that is not exactly aligned and report an error.

[qgis_screenshot.pdf](https://github.com/user-attachments/files/17448195/qgis_screenshot.pdf)
