### ISSUE TITLE
What are correct .bil files in /globe folder

### ISSUE THREAD

**Issue by sambk** [open-afc-project/openafc#198]
Hi openafc team,
I run into the issue below when requesting an AFC query:
> [2024-10-21 04:12:47,991: ERROR/ForkPoolWorker-7] afc_worker.run[deb6d62e-5432-4514-9984-09897a369300]: run(): afc-engine crashed. Task ID=586d4f3b-1a48-47aa-8b01-2ff471d30042, error message:
AFC Engine error: Failed to initialize databases: ERROR: CachedGdalBase::initialize(): GDAL data directory '/mnt/nfs/rat_transfer/globe' does not contain files matching fnmatch pattern '*.bil'

Then I tried to download files from https://www.ngdc.noaa.gov/mgg/topo/gltiles.html and unzip, rename them by adding .bil and place them into /globe folder but afc-engine crashes
> [2024-10-21 04:07:18,766: ERROR/ForkPoolWorker-7] afc_worker.run[a60ee971-6abd-4694-98e0-7496d85d3a10]: run(): afc-engine crashed. Task ID=bd56aba9-8efe-4114-8976-ba5b1fd22a8c, error message:
ERROR 4: `/mnt/nfs/rat_transfer/globe/j10g.bil' not recognized as a supported file format.
Segmentation fault (core dumped)

I also tried to convert to big-endian with command: "_dd if=inputfilename of=outputfilename conv=swab_" for all files before renaming but it does not work, afc-engine still crashes as above.

So could you please support how to prepare the **.bil** files correctly?

Thanks,
Pham Viet Sam

**Comment by FedorSherstyukBroadcom** [comment]
Globe is bizarre file collection.
Raster files should be downloaded from https://www.ngdc.noaa.gov/mgg/topo/gltiles.html, unpacked and renamed to *.bil
Headers (metadata) should be downloaded from here: https://www.ngdc.noaa.gov/mgg/topo/elev/esri/hdr/ and placed alongside .bil files
To certain extent all this described in tools/geo_converters/README.md, but this is an unfinished work (of bringing our geospatial data to order), so read with a grain of salt.
Once Israel will pass its autumn festivities, actual set of data will be put to some public Box (there was an intention to first bring to order than do it, tehn to publish what we actually have... Maybe we'll actually do it at last, as you are a living proof that we should).

**Comment by sambk** [comment]
Hi mmandellrkf and FedorSherstyukBroadcom,
I've tried downloading header files and placing alongside .bil files but it still does not work.

This is globe folder:

> $ ll globe
total 1923924
drwxrwxr-x  2 1004 1004      4096 Thg 10 22 09:24 ./
drwxrwxr-x 20 1004 1004      4096 Thg 10 16 23:06 ../
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 a10g.bil
-rw-r--r--  1 1004 1004       339 Thg 10 22 09:23 a10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 a11g.bil
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 b10g.bil
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 b10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 c10g.bil
-rw-r--r--  1 1004 1004       336 Thg 10 22 09:23 c10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 d10g.bil
-rw-r--r--  1 1004 1004       337 Thg 10 22 09:23 d10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 e10g.bil
-rw-r--r--  1 1004 1004       340 Thg 10 22 09:23 e10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 f10g.bil
-rw-r--r--  1 1004 1004       339 Thg 10 22 09:23 f10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 g10g.bil
-rw-r--r--  1 1004 1004       336 Thg 10 22 09:23 g10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 h10g.bil
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 h10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 i10g.bil
-rw-r--r--  1 1004 1004       340 Thg 10 22 09:23 i10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 j10g.bil
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 j10g.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 k10g.bil
-rw-r--r--  1 1004 1004       337 Thg 10 22 09:23 k10g.hdr
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 l10b.hdr
-rw-rw-r--  1 1004 1004 129600000 Thg 10 22 09:24 l10g.bil
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 l10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 m10g.bil
-rw-r--r--  1 1004 1004       341 Thg 10 22 09:23 m10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 n10g.bil
-rw-r--r--  1 1004 1004       339 Thg 10 22 09:23 n10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 o10g.bil
-rw-r--r--  1 1004 1004       338 Thg 10 22 09:23 o10g.hdr
-rw-rw-r--  1 1004 1004 103680000 Thg 10 22 09:24 p10g.bil
-rw-r--r--  1 1004 1004       339 Thg 10 22 09:23 p10g.hdr


The error is still afc-engine crashes:

> 
[2024-10-22 02:25:26,136: ERROR/ForkPoolWorker-7] afc_worker.run[4126398c-ab39-47d6-a979-856d4b870674]: run(): afc-engine crashed. Task ID=6f617fb7-60b8-465d-aea6-b91b54b1419d, error message:
ERROR 4: `/mnt/nfs/rat_transfer/globe/a11g.bil' not recognized as a supported file format.
Segmentation fault (core dumped)

Could you please suggest what I should check?

Thanks,
Pham Viet Sam

**Comment by mmandellrkf** [comment]
Not sure what is going on here.  One thing to try is to verify we have the same md5sum's.

```
% md5sum *.bil *.hdr
121612dd8b0f8195cdf7a384ec3ec053  a10g.bil
3f6d490ba0d23451989bbf6826c53928  b10g.bil
18df82fa236660671e8016ec8ef018fe  c10g.bil
9b8d7f8a284f2d0100e4521f312ba2c8  d10g.bil
25944a749c47f86c7c7af1c2c235f7dc  e10g.bil
ae19c802aefee92651d3b72f4b02abd8  f10g.bil
6e115441f7e801dc590ec5a5a3ae0f6c  g10g.bil
5ba6044e06d157eb627051f6b38a55d5  h10g.bil
3959d5daa4426373d65fded597474175  i10g.bil
d0da224784b015cb71c3369c5e7dcf08  j10g.bil
699c0b5ea72372e52a1a9b8a01d7950c  k10g.bil
b9307656fa52735d2cc8a72cecf30e19  l10g.bil
813483ae8c68b244227caa7672cf2763  m10g.bil
8425d807bea36d18c2d27994242a488d  n10g.bil
4edf66f5286f19fd71e163ed741214e5  o10g.bil
78f3f1ab19db7e28596ede20474b75b6  p10g.bil
7144e9fb669a51a3e049de2f1ad7f4fe  a10g.hdr
d180278ccc7748b476ab1699e63de5f0  b10g.hdr
81e1eb4e381bd7a70ed86b1c0883ea6d  c10g.hdr
22c21014c6e88932c268331da71a3559  d10g.hdr
4504c8b6686c4a26ae3b2ac3d1f3effc  e10g.hdr
88d58e27b5c40acf9017cfdc18b143e4  f10g.hdr
6c86c8c25b5e3f25cfaf23793c86a4e4  g10g.hdr
dc8050225378ab442bc0acd6d2d73b76  h10g.hdr
4699e2c54ecbdcf03ffb2661ef7d41ba  i10g.hdr
634807ac0feee02341efec4519886143  j10g.hdr
b0776b967de702e14eb37d556455e326  k10g.hdr
23684a0cd596642a904289388b031109  l10g.hdr
dbd0979e87e8dd03566b65b8054c4820  m10g.hdr
64a50b79e81dcd7fa1791b914d6eb6d6  n10g.hdr
4b56876dfd3ac78ded95b5545127e90d  o10g.hdr
f131c0fc119739b5dca489cba7e1db63  p10g.hdr
```

Another thing to try is to confirm that gdalinfo can read the files:

```
% gdalinfo a10g.bil 
Driver: EHdr/ESRI .hdr Labelled
Files: a10g.bil
       a10g.hdr
Size is 10800, 4800
Origin = (-179.999999999999488,89.999999999999503)
Pixel Size = (0.008333333333000,-0.008333333333000)
Corner Coordinates:
Upper Left  (-180.0000000,  90.0000000) 
Lower Left  (-180.0000000,  50.0000000) 
Upper Right ( -90.0000000,  90.0000000) 
Lower Right ( -90.0000000,  50.0000000) 
Center      (-135.0000000,  70.0000000) 
Band 1 Block=10800x1 Type=Int16, ColorInterp=Undefined
  NoData Value=-5e+02
```

**Comment by sambk** [comment]
Hi @mmandellrkf,
Thank you for your great support. After comparing your info and mine, I've detected that there is not "a11g.hdr" file for "a11g.bil". Not sure why a11g is in all10g.zip. I've tried to delete that file and it works.  **So is it ok to delete a11g.bil?**

Btw, I would like to confirm about this: The instruction on https://www.ngdc.noaa.gov/mgg/topo/report/s11/s11Giii.html makes me confused that whether I have to convert the files for big endian? I've tried and little and big endian both work. **So please help me confirm**

Thanks,
Pham Viet Sam

**Comment by FedorSherstyukBroadcom** [comment]
a11g is a revised version of a10g (see here: https://www.ngdc.noaa.gov/mgg/topo/report/s11/s11A.html ).
You may remove it, or you may remove a10.g and rename a11g to a10g.
Frankly, Globe data resolution that it is beyond the very last resort, so for practical use you better have some more precise terrain model

**Comment by sambk** [comment]
Thank you for your support
