### ISSUE TITLE
Migrated - 'ITM with building data' propagation model is broken (837)

### ISSUE THREAD

**Issue by mgelman-rkf** [open-afc-project/openafc#2]

**Comment by mgelman-rkf** [comment]
There was a change in parameters that did not get applied to these cases.
win2Confidence has been replaced with three parameters:
win2ConfidenceCombined
win2ConfidenceLOS
win2ConfidenceNLOS

**Comment by farinazedalat** [comment]
Validated that the this propagation model works after this change. Note that currently using ITM with building database runs very slow for large distances and we would get timeout for long distances (e.g. the default 200 km). As such, the test was run for a short distance of 2km.
[2tests.zip](https://github.com/user-attachments/files/16785157/2tests.zip)
