### ISSUE TITLE
ALS-Siphon image build failed starting from 4/15

### ISSUE THREAD

**Issue by WFA-hhsieh** [open-afc-project/openafc#25]
Starting from 4/15, ALS-Siphon image build failed.
The root cause is the dependency APK package py3-confluent-kafka has been rebuild against Python 3.12 in latest version.
https://git.alpinelinux.org/aports/commit/testing/py3-confluent-kafka?id=d6e150e93225793d344d15222f3d7b90be2d0381

![image](https://github.com/open-afc-project/openafc/assets/91172474/9aecfe08-82c5-4f30-b41b-d4171c010240)

**Comment by dr942120** [comment]
@FedorSherstyukBroadcom 
Fedor, could you please take a look?
