### ISSUE TITLE
NLCD tiling code lost in merge issue

### ISSUE THREAD

**Issue by mgelman-rkf** [open-afc-project/openafc#9]
> Hi OpenAFC Team,
> 
> We found there are code blocks are accidentally deleted in the PR - 851 format code for release (#854).
> 
> One of the missing code blocks is Tiled NLCD change from Fedor

I will work with Mike Mandell to resolve the discrepancy

**Comment by dr942120** [comment]
@mgelman-rkf @farinazedalat 
Hi Michael/Mike
Any updates here?
